<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>XMLSerializer</RootNamespace>
    <AssemblyName>DWSIM.XMLSerializer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Core" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DWSIM.Interfaces\DWSIM.Interfaces.vbproj" />
  </ItemGroup>

</Project>
