<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DWSIMCore.Foundation</RootNamespace>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Bitmaps\attention.png" />
    <None Remove="Assets\Bitmaps\clock.png" />
    <None Remove="Assets\Bitmaps\clock2.png" />
    <None Remove="Assets\Bitmaps\control_panel.png" />
    <None Remove="Assets\Bitmaps\flow.png" />
    <None Remove="Assets\Bitmaps\lightning_bolt.png" />
    <None Remove="Assets\Bitmaps\pressure.png" />
    <None Remove="Assets\Bitmaps\switch_off.png" />
    <None Remove="Assets\Bitmaps\switch_on.png" />
    <None Remove="Assets\Bitmaps\temperature.png" />
    <None Remove="Assets\Bitmaps\volume.png" />
    <None Remove="Assets\Bitmaps\weight.png" />
    <None Remove="Assets\Fonts\Asap-Bold.ttf" />
    <None Remove="Assets\Fonts\Asap-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\Asap-Italic.ttf" />
    <None Remove="Assets\Fonts\Asap-Medium.ttf" />
    <None Remove="Assets\Fonts\Asap-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\Asap-Regular.ttf" />
    <None Remove="Assets\Fonts\Asap-SemiBold.ttf" />
    <None Remove="Assets\Fonts\Asap-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-Medium.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Black.ttf" />
    <None Remove="Assets\Fonts\Barlow-BlackItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Bold.ttf" />
    <None Remove="Assets\Fonts\Barlow-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\Barlow-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\Barlow-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Italic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Light.ttf" />
    <None Remove="Assets\Fonts\Barlow-LightItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Medium.ttf" />
    <None Remove="Assets\Fonts\Barlow-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Regular.ttf" />
    <None Remove="Assets\Fonts\Barlow-SemiBold.ttf" />
    <None Remove="Assets\Fonts\Barlow-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Thin.ttf" />
    <None Remove="Assets\Fonts\Barlow-ThinItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Black.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-BlackItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Light.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-LightItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Medium.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Thin.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ThinItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Black.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-BlackItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Light.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-LightItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Medium.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Thin.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ThinItalic.ttf" />
    <None Remove="Assets\Fonts\digital7_mono.ttf" />
    <None Remove="Assets\Fonts\digital7_mono_italic.ttf" />
    <None Remove="Assets\Fonts\Fonts.txt" />
    <None Remove="Assets\Fonts\JetBrainsMono-Bold.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Italic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Light.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-LightItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Medium.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Regular.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-SemiBold.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Thin.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ThinItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Bold.ttf" />
    <None Remove="Assets\Fonts\OpenSans-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Italic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Light.ttf" />
    <None Remove="Assets\Fonts\OpenSans-LightItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Medium.ttf" />
    <None Remove="Assets\Fonts\OpenSans-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Regular.ttf" />
    <None Remove="Assets\Fonts\OpenSans-SemiBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Bold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Italic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Light.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-LightItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Medium.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Regular.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Light.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-LightItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Medium.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Black.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-BlackItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Bold.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Italic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Light.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-LightItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Regular.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-SemiBold.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-SemiBoldItalic.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Bitmaps\attention.png" />
    <EmbeddedResource Include="Assets\Bitmaps\clock.png" />
    <EmbeddedResource Include="Assets\Bitmaps\clock2.png" />
    <EmbeddedResource Include="Assets\Bitmaps\control_panel.png" />
    <EmbeddedResource Include="Assets\Bitmaps\flow.png" />
    <EmbeddedResource Include="Assets\Bitmaps\lightning_bolt.png" />
    <EmbeddedResource Include="Assets\Bitmaps\pressure.png" />
    <EmbeddedResource Include="Assets\Bitmaps\switch_off.png" />
    <EmbeddedResource Include="Assets\Bitmaps\switch_on.png" />
    <EmbeddedResource Include="Assets\Bitmaps\temperature.png" />
    <EmbeddedResource Include="Assets\Bitmaps\volume.png" />
    <EmbeddedResource Include="Assets\Bitmaps\weight.png" />
    <EmbeddedResource Include="Assets\Fonts\Asap-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Black.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-BlackItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Thin.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ThinItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Black.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-BlackItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Thin.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ThinItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Black.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-BlackItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Thin.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ThinItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\digital7_mono.ttf" />
    <EmbeddedResource Include="Assets\Fonts\digital7_mono_italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Fonts.txt" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Thin.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ThinItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Black.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-BlackItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-SemiBoldItalic.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="OxyPlot.Core" Version="2.1.0" />
    <PackageReference Include="SharpZipLib" Version="1.3.3" />
    <PackageReference Include="SkiaSharp" Version="2.80.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="FlowsheetObjects\UnitOps\" />
    <Folder Include="Flowsheet\Base\" />
    <Folder Include="Thermo\" />
  </ItemGroup>

</Project>
