<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DWSIMCore.Foundation</RootNamespace>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="OxyPlot.Core" Version="2.1.0" />
    <PackageReference Include="SkiaSharp" Version="2.80.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="FlowsheetObjects\UnitOps\" />
    <Folder Include="FlowsheetObjects\Streams\" />
    <Folder Include="Thermo\" />
  </ItemGroup>

</Project>
