<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DWSIMCore.Foundation</RootNamespace>
    <TargetFramework>net6.0</TargetFramework>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Authors>Daniel Medeiros</Authors>
    <Company>Daniel Medeiros</Company>
    <Copyright>Copyright 2022 Daniel Wagner Oliveira de Medeiros</Copyright>
    <PackageProjectUrl>https://dwsim.org</PackageProjectUrl>
    <Product>DWSIM Simulator Core Library (.NET 6)</Product>
    <Description>Core Library for DWSIM Simulator, including Base Classes (Compounds, Reactions, etc), Auxiliary Classes (Math, Optimizers, Units of Measure, XML Serializer), Streams, Unit Operations and Thermodynamic Models.</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Bitmaps\attention.png" />
    <None Remove="Assets\Bitmaps\clock.png" />
    <None Remove="Assets\Bitmaps\clock2.png" />
    <None Remove="Assets\Bitmaps\control_panel.png" />
    <None Remove="Assets\Bitmaps\flow.png" />
    <None Remove="Assets\Bitmaps\lightning_bolt.png" />
    <None Remove="Assets\Bitmaps\pressure.png" />
    <None Remove="Assets\Bitmaps\switch_off.png" />
    <None Remove="Assets\Bitmaps\switch_on.png" />
    <None Remove="Assets\Bitmaps\temperature.png" />
    <None Remove="Assets\Bitmaps\volume.png" />
    <None Remove="Assets\Bitmaps\weight.png" />
    <None Remove="Assets\Icons\add.png" />
    <None Remove="Assets\Icons\arrows_4_way.png" />
    <None Remove="Assets\Icons\arrow_down.png" />
    <None Remove="Assets\Icons\arrow_in1.png" />
    <None Remove="Assets\Icons\arrow_left.png" />
    <None Remove="Assets\Icons\arrow_right.png" />
    <None Remove="Assets\Icons\arrow_rotate_clockwise.png" />
    <None Remove="Assets\Icons\arrow_up.png" />
    <None Remove="Assets\Icons\bullet_lightning.png" />
    <None Remove="Assets\Icons\bullet_sparkle.png" />
    <None Remove="Assets\Icons\bullet_tick.png" />
    <None Remove="Assets\Icons\chart_line.png" />
    <None Remove="Assets\Icons\cog.png" />
    <None Remove="Assets\Icons\col_abs_16.png" />
    <None Remove="Assets\Icons\col_abs_32.png" />
    <None Remove="Assets\Icons\col_dc_16.png" />
    <None Remove="Assets\Icons\col_dc_32.png" />
    <None Remove="Assets\Icons\col_rebabs_16.png" />
    <None Remove="Assets\Icons\col_rebabs_32.png" />
    <None Remove="Assets\Icons\col_rflabs_16.png" />
    <None Remove="Assets\Icons\col_rflabs_32.png" />
    <None Remove="Assets\Icons\col_sc_16.png" />
    <None Remove="Assets\Icons\col_sc_32.png" />
    <None Remove="Assets\Icons\connect.png" />
    <None Remove="Assets\Icons\connect1.png" />
    <None Remove="Assets\Icons\control_play.png" />
    <None Remove="Assets\Icons\copy.gif" />
    <None Remove="Assets\Icons\cross.png" />
    <None Remove="Assets\Icons\delete.png" />
    <None Remove="Assets\Icons\disconnect.png" />
    <None Remove="Assets\Icons\disk.png" />
    <None Remove="Assets\Icons\fast_forward.png" />
    <None Remove="Assets\Icons\folder_page_white.png" />
    <None Remove="Assets\Icons\help-browser1.png" />
    <None Remove="Assets\Icons\icons8-spy_male.png" />
    <None Remove="Assets\Icons\information.png" />
    <None Remove="Assets\Icons\input.png" />
    <None Remove="Assets\Icons\lightning.png" />
    <None Remove="Assets\Icons\lock.png" />
    <None Remove="Assets\Icons\lock_open.png" />
    <None Remove="Assets\Icons\lo_adjust_16.png" />
    <None Remove="Assets\Icons\lo_adjust_32.png" />
    <None Remove="Assets\Icons\lo_enrecy_16.png" />
    <None Remove="Assets\Icons\lo_enrecy_32.png" />
    <None Remove="Assets\Icons\lo_recy_16.png" />
    <None Remove="Assets\Icons\lo_recy_32.png" />
    <None Remove="Assets\Icons\lo_spec_16.png" />
    <None Remove="Assets\Icons\lo_spec_32.png" />
    <None Remove="Assets\Icons\new.png" />
    <None Remove="Assets\Icons\page_white_gear.png" />
    <None Remove="Assets\Icons\page_white_magnify.png" />
    <None Remove="Assets\Icons\paste_plain.png" />
    <None Remove="Assets\Icons\printer.png" />
    <None Remove="Assets\Icons\printer_add.png" />
    <None Remove="Assets\Icons\rewind.png" />
    <None Remove="Assets\Icons\re_conv_16.png" />
    <None Remove="Assets\Icons\re_conv_32.png" />
    <None Remove="Assets\Icons\re_cstr_16.png" />
    <None Remove="Assets\Icons\re_cstr_32.png" />
    <None Remove="Assets\Icons\re_equi_16.png" />
    <None Remove="Assets\Icons\re_equi_32.png" />
    <None Remove="Assets\Icons\re_gibbs_16.png" />
    <None Remove="Assets\Icons\re_gibbs_32.png" />
    <None Remove="Assets\Icons\re_pfr_16.png" />
    <None Remove="Assets\Icons\re_pfr_32.png" />
    <None Remove="Assets\Icons\script_code.png" />
    <None Remove="Assets\Icons\script_code1.png" />
    <None Remove="Assets\Icons\shape_square_add.png" />
    <None Remove="Assets\Icons\shape_square_delete.png" />
    <None Remove="Assets\Icons\Straight-tube_heat_exchanger_1-pass.PNG" />
    <None Remove="Assets\Icons\Straight-tube_heat_exchanger_2-pass.PNG" />
    <None Remove="Assets\Icons\stream_en_16.png" />
    <None Remove="Assets\Icons\stream_en_32.png" />
    <None Remove="Assets\Icons\stream_mat_16.png" />
    <None Remove="Assets\Icons\stream_mat_32.png" />
    <None Remove="Assets\Icons\tag_blue.png" />
    <None Remove="Assets\Icons\tick.png" />
    <None Remove="Assets\Icons\turn_left.png" />
    <None Remove="Assets\Icons\turn_right.png" />
    <None Remove="Assets\Icons\uo_compr_16.png" />
    <None Remove="Assets\Icons\uo_compr_32.png" />
    <None Remove="Assets\Icons\uo_compsep_16.png" />
    <None Remove="Assets\Icons\uo_compsep_32.png" />
    <None Remove="Assets\Icons\uo_cooler_16.png" />
    <None Remove="Assets\Icons\uo_cooler_32.png" />
    <None Remove="Assets\Icons\uo_co_16.png" />
    <None Remove="Assets\Icons\uo_co_32.png" />
    <None Remove="Assets\Icons\uo_custom_16.png" />
    <None Remove="Assets\Icons\uo_custom_32.png" />
    <None Remove="Assets\Icons\uo_excel_16.png" />
    <None Remove="Assets\Icons\uo_excel_32.png" />
    <None Remove="Assets\Icons\uo_expan_16.png" />
    <None Remove="Assets\Icons\uo_expan_32.png" />
    <None Remove="Assets\Icons\uo_filter_16.png" />
    <None Remove="Assets\Icons\uo_filter_32.png" />
    <None Remove="Assets\Icons\uo_flash_16.png" />
    <None Remove="Assets\Icons\uo_flash_32.png" />
    <None Remove="Assets\Icons\uo_fs_16.png" />
    <None Remove="Assets\Icons\uo_fs_32.png" />
    <None Remove="Assets\Icons\uo_heater_16.png" />
    <None Remove="Assets\Icons\uo_heater_32.png" />
    <None Remove="Assets\Icons\uo_hx_16.png" />
    <None Remove="Assets\Icons\uo_hx_32.png" />
    <None Remove="Assets\Icons\uo_mixer_16.png" />
    <None Remove="Assets\Icons\uo_mixer_32.png" />
    <None Remove="Assets\Icons\uo_orifice_16.png" />
    <None Remove="Assets\Icons\uo_orifice_32.png" />
    <None Remove="Assets\Icons\uo_pipe_16.png" />
    <None Remove="Assets\Icons\uo_pipe_32.png" />
    <None Remove="Assets\Icons\uo_pump_16.png" />
    <None Remove="Assets\Icons\uo_pump_32.png" />
    <None Remove="Assets\Icons\uo_solidsep_16.png" />
    <None Remove="Assets\Icons\uo_solidsep_32.png" />
    <None Remove="Assets\Icons\uo_split_16.png" />
    <None Remove="Assets\Icons\uo_split_32.png" />
    <None Remove="Assets\Icons\uo_tank_16.png" />
    <None Remove="Assets\Icons\uo_tank_32.png" />
    <None Remove="Assets\Icons\uo_valve_16.png" />
    <None Remove="Assets\Icons\uo_valve_32.png" />
    <None Remove="Assets\Thermo\Databases\Artistic_license_2_0.txt" />
    <None Remove="Assets\Thermo\Databases\biod_db.xml" />
    <None Remove="Assets\Thermo\Databases\chedl_thermo.json" />
    <None Remove="Assets\Thermo\Databases\chemsep1.xml" />
    <None Remove="Assets\Thermo\Databases\chemsep2.xml" />
    <None Remove="Assets\Thermo\Databases\coolprop.xml" />
    <None Remove="Assets\Thermo\Databases\CoolPropIncompMixtures.txt" />
    <None Remove="Assets\Thermo\Databases\CoolPropIncompPure.txt" />
    <None Remove="Assets\Thermo\Databases\dwsim.xml" />
    <None Remove="Assets\Thermo\Databases\electrolyte.xml" />
    <None Remove="Assets\Fonts\Asap-Bold.ttf" />
    <None Remove="Assets\Fonts\Asap-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\Asap-Italic.ttf" />
    <None Remove="Assets\Fonts\Asap-Medium.ttf" />
    <None Remove="Assets\Fonts\Asap-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\Asap-Regular.ttf" />
    <None Remove="Assets\Fonts\Asap-SemiBold.ttf" />
    <None Remove="Assets\Fonts\Asap-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-Medium.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\AsapCondensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Black.ttf" />
    <None Remove="Assets\Fonts\Barlow-BlackItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Bold.ttf" />
    <None Remove="Assets\Fonts\Barlow-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\Barlow-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\Barlow-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Italic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Light.ttf" />
    <None Remove="Assets\Fonts\Barlow-LightItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Medium.ttf" />
    <None Remove="Assets\Fonts\Barlow-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Regular.ttf" />
    <None Remove="Assets\Fonts\Barlow-SemiBold.ttf" />
    <None Remove="Assets\Fonts\Barlow-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\Barlow-Thin.ttf" />
    <None Remove="Assets\Fonts\Barlow-ThinItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Black.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-BlackItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Light.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-LightItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Medium.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-Thin.ttf" />
    <None Remove="Assets\Fonts\BarlowCondensed-ThinItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Black.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-BlackItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Light.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-LightItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Medium.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-Thin.ttf" />
    <None Remove="Assets\Fonts\BarlowSemiCondensed-ThinItalic.ttf" />
    <None Remove="Assets\Fonts\digital7_mono.ttf" />
    <None Remove="Assets\Fonts\digital7_mono_italic.ttf" />
    <None Remove="Assets\Fonts\Fonts.txt" />
    <None Remove="Assets\Fonts\JetBrainsMono-Bold.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Italic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Light.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-LightItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Medium.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Regular.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-SemiBold.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-Thin.ttf" />
    <None Remove="Assets\Fonts\JetBrainsMono-ThinItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Bold.ttf" />
    <None Remove="Assets\Fonts\OpenSans-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Italic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Light.ttf" />
    <None Remove="Assets\Fonts\OpenSans-LightItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Medium.ttf" />
    <None Remove="Assets\Fonts\OpenSans-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans-Regular.ttf" />
    <None Remove="Assets\Fonts\OpenSans-SemiBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Bold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Italic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Light.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-LightItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Medium.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-Regular.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_Condensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Bold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-ExtraBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-ExtraBoldItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Italic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Light.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-LightItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Medium.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-MediumItalic.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-Regular.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-SemiBold.ttf" />
    <None Remove="Assets\Fonts\OpenSans_SemiCondensed-SemiBoldItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Black.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-BlackItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Bold.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-BoldItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-ExtraLight.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-ExtraLightItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Italic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Light.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-LightItalic.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-Regular.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-SemiBold.ttf" />
    <None Remove="Assets\Fonts\SourceSansPro-SemiBoldItalic.ttf" />
    <None Remove="Assets\Thermo\biod_intparm_nrtl.dat" />
    <None Remove="Assets\Thermo\CAS_IDs.txt" />
    <None Remove="Assets\Thermo\ChemSep_IDs.txt" />
    <None Remove="Assets\Thermo\csid.dat" />
    <None Remove="Assets\Thermo\diel.dat" />
    <None Remove="Assets\Thermo\dielectricconstants.txt" />
    <None Remove="Assets\Thermo\elements.txt" />
    <None Remove="Assets\Thermo\ExUNIQUAC_RiQi.txt" />
    <None Remove="Assets\Thermo\ExUNIQUAC_uij.txt" />
    <None Remove="Assets\Thermo\henry.txt" />
    <None Remove="Assets\Thermo\hid_chenguo.dat" />
    <None Remove="Assets\Thermo\hid_klaudasandler.dat" />
    <None Remove="Assets\Thermo\hid_vdwp_pp.dat" />
    <None Remove="Assets\Thermo\inib.dat" />
    <None Remove="Assets\Thermo\jobackgroups.txt" />
    <None Remove="Assets\Thermo\kij_pr.dat" />
    <None Remove="Assets\Thermo\kij_srk.dat" />
    <None Remove="Assets\Thermo\kij_srk.txt" />
    <None Remove="Assets\Thermo\LIQUAC2_IP.txt" />
    <None Remove="Assets\Thermo\LIQUAC2_RiQi.txt" />
    <None Remove="Assets\Thermo\lkp_ip.dat" />
    <None Remove="Assets\Thermo\modfac.txt" />
    <None Remove="Assets\Thermo\modfac_ip.txt" />
    <None Remove="Assets\Thermo\NIST-MODFAC_IP.txt" />
    <None Remove="Assets\Thermo\NIST-MODFAC_RiQi.txt" />
    <None Remove="Assets\Thermo\nrtl.dat" />
    <None Remove="Assets\Thermo\nrtl.ipd" />
    <None Remove="Assets\Thermo\pcsaft.dat" />
    <None Remove="Assets\Thermo\pcsaft_ip.dat" />
    <None Remove="Assets\Thermo\pr.ipd" />
    <None Remove="Assets\Thermo\prsv2.dat" />
    <None Remove="Assets\Thermo\prsv2_ip.dat" />
    <None Remove="Assets\Thermo\prsv2_ip_vl.dat" />
    <None Remove="Assets\Thermo\pr_ip.dat" />
    <None Remove="Assets\Thermo\srk.ipd" />
    <None Remove="Assets\Thermo\srk_ip.dat" />
    <None Remove="Assets\Thermo\swreactions.dwrxm" />
    <None Remove="Assets\Thermo\unifac.txt" />
    <None Remove="Assets\Thermo\unifac_ip.txt" />
    <None Remove="Assets\Thermo\unifac_ll_ip.txt" />
    <None Remove="Assets\Thermo\uniquac.dat" />
    <None Remove="Assets\Thermo\uniquac.ipd" />
    <None Remove="Assets\Thermo\uniquacip.dat" />
    <None Remove="Assets\Thermo\wilson.ipd" />
    <None Remove="Assets\Thermo\wilson_bips.csv" />
    <None Remove="Libraries\CapeOpen.dll" />
    <None Remove="Libraries\CoolProp.dll" />
    <None Remove="Libraries\CoolPropInterface.dll" />
    <None Remove="Libraries\Cureos.Numerics.dll" />
    <None Remove="Libraries\DotNumerics.dll" />
    <None Remove="Libraries\IpOpt39.dll" />
    <None Remove="Libraries\IpOptFSS.dll" />
    <None Remove="Libraries\libifcoremd.dll" />
    <None Remove="Libraries\libiomp5md.dll" />
    <None Remove="Libraries\Mapack.dll" />
    <None Remove="Libraries\msvcp140.dll" />
    <None Remove="Libraries\PetAz.dll" />
    <None Remove="Libraries\svml_dispmd.dll" />
    <None Remove="Libraries\vcruntime140.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Libraries\CapeOpen.dll" />
    <Content Include="Libraries\CoolProp.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Libraries\CoolPropInterface.dll" />
    <Content Include="Libraries\Cureos.Numerics.dll" />
    <Content Include="Libraries\DotNumerics.dll" />
    <Content Include="Libraries\IpOpt39.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Libraries\IpOptFSS.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Libraries\libifcoremd.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Libraries\libiomp5md.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Libraries\Mapack.dll" />
    <Content Include="Libraries\msvcp140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Libraries\PetAz.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Libraries\svml_dispmd.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Libraries\vcruntime140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Bitmaps\attention.png" />
    <EmbeddedResource Include="Assets\Bitmaps\clock.png" />
    <EmbeddedResource Include="Assets\Bitmaps\clock2.png" />
    <EmbeddedResource Include="Assets\Bitmaps\control_panel.png" />
    <EmbeddedResource Include="Assets\Bitmaps\flow.png" />
    <EmbeddedResource Include="Assets\Bitmaps\lightning_bolt.png" />
    <EmbeddedResource Include="Assets\Bitmaps\pressure.png" />
    <EmbeddedResource Include="Assets\Bitmaps\switch_off.png" />
    <EmbeddedResource Include="Assets\Bitmaps\switch_on.png" />
    <EmbeddedResource Include="Assets\Bitmaps\temperature.png" />
    <EmbeddedResource Include="Assets\Bitmaps\volume.png" />
    <EmbeddedResource Include="Assets\Bitmaps\weight.png" />
    <EmbeddedResource Include="Assets\Icons\add.png" />
    <EmbeddedResource Include="Assets\Icons\arrows_4_way.png" />
    <EmbeddedResource Include="Assets\Icons\arrow_down.png" />
    <EmbeddedResource Include="Assets\Icons\arrow_in1.png" />
    <EmbeddedResource Include="Assets\Icons\arrow_left.png" />
    <EmbeddedResource Include="Assets\Icons\arrow_right.png" />
    <EmbeddedResource Include="Assets\Icons\arrow_rotate_clockwise.png" />
    <EmbeddedResource Include="Assets\Icons\arrow_up.png" />
    <EmbeddedResource Include="Assets\Icons\bullet_lightning.png" />
    <EmbeddedResource Include="Assets\Icons\bullet_sparkle.png" />
    <EmbeddedResource Include="Assets\Icons\bullet_tick.png" />
    <EmbeddedResource Include="Assets\Icons\chart_line.png" />
    <EmbeddedResource Include="Assets\Icons\cog.png" />
    <EmbeddedResource Include="Assets\Icons\col_abs_16.png" />
    <EmbeddedResource Include="Assets\Icons\col_abs_32.png" />
    <EmbeddedResource Include="Assets\Icons\col_dc_16.png" />
    <EmbeddedResource Include="Assets\Icons\col_dc_32.png" />
    <EmbeddedResource Include="Assets\Icons\col_rebabs_16.png" />
    <EmbeddedResource Include="Assets\Icons\col_rebabs_32.png" />
    <EmbeddedResource Include="Assets\Icons\col_rflabs_16.png" />
    <EmbeddedResource Include="Assets\Icons\col_rflabs_32.png" />
    <EmbeddedResource Include="Assets\Icons\col_sc_16.png" />
    <EmbeddedResource Include="Assets\Icons\col_sc_32.png" />
    <EmbeddedResource Include="Assets\Icons\connect.png" />
    <EmbeddedResource Include="Assets\Icons\connect1.png" />
    <EmbeddedResource Include="Assets\Icons\control_play.png" />
    <EmbeddedResource Include="Assets\Icons\copy.gif" />
    <EmbeddedResource Include="Assets\Icons\cross.png" />
    <EmbeddedResource Include="Assets\Icons\delete.png" />
    <EmbeddedResource Include="Assets\Icons\disconnect.png" />
    <EmbeddedResource Include="Assets\Icons\disk.png" />
    <EmbeddedResource Include="Assets\Icons\fast_forward.png" />
    <EmbeddedResource Include="Assets\Icons\folder_page_white.png" />
    <EmbeddedResource Include="Assets\Icons\help-browser1.png" />
    <EmbeddedResource Include="Assets\Icons\icons8-spy_male.png" />
    <EmbeddedResource Include="Assets\Icons\information.png" />
    <EmbeddedResource Include="Assets\Icons\input.png" />
    <EmbeddedResource Include="Assets\Icons\lightning.png" />
    <EmbeddedResource Include="Assets\Icons\lock.png" />
    <EmbeddedResource Include="Assets\Icons\lock_open.png" />
    <EmbeddedResource Include="Assets\Icons\lo_adjust_16.png" />
    <EmbeddedResource Include="Assets\Icons\lo_adjust_32.png" />
    <EmbeddedResource Include="Assets\Icons\lo_enrecy_16.png" />
    <EmbeddedResource Include="Assets\Icons\lo_enrecy_32.png" />
    <EmbeddedResource Include="Assets\Icons\lo_recy_16.png" />
    <EmbeddedResource Include="Assets\Icons\lo_recy_32.png" />
    <EmbeddedResource Include="Assets\Icons\lo_spec_16.png" />
    <EmbeddedResource Include="Assets\Icons\lo_spec_32.png" />
    <EmbeddedResource Include="Assets\Icons\new.png" />
    <EmbeddedResource Include="Assets\Icons\page_white_gear.png" />
    <EmbeddedResource Include="Assets\Icons\page_white_magnify.png" />
    <EmbeddedResource Include="Assets\Icons\paste_plain.png" />
    <EmbeddedResource Include="Assets\Icons\printer.png" />
    <EmbeddedResource Include="Assets\Icons\printer_add.png" />
    <EmbeddedResource Include="Assets\Icons\rewind.png" />
    <EmbeddedResource Include="Assets\Icons\re_conv_16.png" />
    <EmbeddedResource Include="Assets\Icons\re_conv_32.png" />
    <EmbeddedResource Include="Assets\Icons\re_cstr_16.png" />
    <EmbeddedResource Include="Assets\Icons\re_cstr_32.png" />
    <EmbeddedResource Include="Assets\Icons\re_equi_16.png" />
    <EmbeddedResource Include="Assets\Icons\re_equi_32.png" />
    <EmbeddedResource Include="Assets\Icons\re_gibbs_16.png" />
    <EmbeddedResource Include="Assets\Icons\re_gibbs_32.png" />
    <EmbeddedResource Include="Assets\Icons\re_pfr_16.png" />
    <EmbeddedResource Include="Assets\Icons\re_pfr_32.png" />
    <EmbeddedResource Include="Assets\Icons\script_code.png" />
    <EmbeddedResource Include="Assets\Icons\script_code1.png" />
    <EmbeddedResource Include="Assets\Icons\shape_square_add.png" />
    <EmbeddedResource Include="Assets\Icons\shape_square_delete.png" />
    <EmbeddedResource Include="Assets\Icons\Straight-tube_heat_exchanger_1-pass.PNG" />
    <EmbeddedResource Include="Assets\Icons\Straight-tube_heat_exchanger_2-pass.PNG" />
    <EmbeddedResource Include="Assets\Icons\stream_en_16.png" />
    <EmbeddedResource Include="Assets\Icons\stream_en_32.png" />
    <EmbeddedResource Include="Assets\Icons\stream_mat_16.png" />
    <EmbeddedResource Include="Assets\Icons\stream_mat_32.png" />
    <EmbeddedResource Include="Assets\Icons\tag_blue.png" />
    <EmbeddedResource Include="Assets\Icons\tick.png" />
    <EmbeddedResource Include="Assets\Icons\turn_left.png" />
    <EmbeddedResource Include="Assets\Icons\turn_right.png" />
    <EmbeddedResource Include="Assets\Icons\uo_compr_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_compr_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_compsep_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_compsep_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_cooler_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_cooler_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_co_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_co_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_custom_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_custom_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_excel_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_excel_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_expan_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_expan_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_filter_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_filter_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_flash_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_flash_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_fs_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_fs_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_heater_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_heater_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_hx_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_hx_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_mixer_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_mixer_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_orifice_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_orifice_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_pipe_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_pipe_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_pump_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_pump_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_solidsep_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_solidsep_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_split_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_split_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_tank_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_tank_32.png" />
    <EmbeddedResource Include="Assets\Icons\uo_valve_16.png" />
    <EmbeddedResource Include="Assets\Icons\uo_valve_32.png" />
    <EmbeddedResource Include="Assets\Thermo\Databases\Artistic_license_2_0.txt" />
    <EmbeddedResource Include="Assets\Thermo\Databases\biod_db.xml" />
    <EmbeddedResource Include="Assets\Thermo\Databases\chedl_thermo.json" />
    <EmbeddedResource Include="Assets\Thermo\Databases\chemsep1.xml" />
    <EmbeddedResource Include="Assets\Thermo\Databases\chemsep2.xml" />
    <EmbeddedResource Include="Assets\Thermo\Databases\coolprop.xml" />
    <EmbeddedResource Include="Assets\Thermo\Databases\CoolPropIncompMixtures.txt" />
    <EmbeddedResource Include="Assets\Thermo\Databases\CoolPropIncompPure.txt" />
    <EmbeddedResource Include="Assets\Thermo\Databases\dwsim.xml" />
    <EmbeddedResource Include="Assets\Thermo\Databases\electrolyte.xml" />
    <EmbeddedResource Include="Assets\Fonts\Asap-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Asap-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\AsapCondensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Black.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-BlackItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-Thin.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Barlow-ThinItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Black.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-BlackItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-Thin.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowCondensed-ThinItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Black.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-BlackItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-Thin.ttf" />
    <EmbeddedResource Include="Assets\Fonts\BarlowSemiCondensed-ThinItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\digital7_mono.ttf" />
    <EmbeddedResource Include="Assets\Fonts\digital7_mono_italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\Fonts.txt" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-Thin.ttf" />
    <EmbeddedResource Include="Assets\Fonts\JetBrainsMono-ThinItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_Condensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-ExtraBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-ExtraBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Medium.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-MediumItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\OpenSans_SemiCondensed-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Black.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-BlackItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Bold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-BoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-ExtraLight.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-ExtraLightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Italic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Light.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-LightItalic.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-Regular.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-SemiBold.ttf" />
    <EmbeddedResource Include="Assets\Fonts\SourceSansPro-SemiBoldItalic.ttf" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\biod_intparm_nrtl.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\CAS_IDs.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\ChemSep_IDs.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\csid.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\diel.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\dielectricconstants.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\elements.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\ExUNIQUAC_RiQi.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\ExUNIQUAC_uij.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\henry.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\hid_chenguo.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\hid_klaudasandler.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\hid_vdwp_pp.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\inib.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\jobackgroups.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\kij_pr.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\kij_srk.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\kij_srk.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\LIQUAC2_IP.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\LIQUAC2_RiQi.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\lkp_ip.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\modfac.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\modfac_ip.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\NIST-MODFAC_IP.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\NIST-MODFAC_RiQi.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\nrtl.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\nrtl.ipd" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\pcsaft.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\pcsaft_ip.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\pr.ipd" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\prsv2.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\prsv2_ip.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\prsv2_ip_vl.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\pr_ip.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\srk.ipd" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\srk_ip.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\swreactions.dwrxm" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\unifac.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\unifac_ip.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\unifac_ll_ip.txt" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\uniquac.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\uniquac.ipd" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\uniquacip.dat" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\wilson.ipd" />
    <EmbeddedResource Include="Assets\Thermo\ModelParameters\wilson_bips.csv" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
    <PackageReference Include="FileHelpers" Version="3.5.1" />
    <PackageReference Include="Flee" Version="2.0.0" />
    <PackageReference Include="IronPython" Version="3.4.0-beta1" />
    <PackageReference Include="Mages" Version="2.0.0" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="OxyPlot.Core" Version="2.1.0" />
    <PackageReference Include="SharpZipLib" Version="1.3.3" />
    <PackageReference Include="SkiaSharp" Version="2.80.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Flowsheet\Base\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CapeOpen">
      <HintPath>Libraries\CapeOpen.dll</HintPath>
    </Reference>
    <Reference Include="Cureos.Numerics">
      <HintPath>Libraries\Cureos.Numerics.dll</HintPath>
    </Reference>
    <Reference Include="DWSIM.MathOps.DotNumerics">
      <HintPath>Libraries\DotNumerics.dll</HintPath>
    </Reference>
    <Reference Include="DWSIM.Thermodynamics.CoolPropInterface">
      <HintPath>Libraries\CoolPropInterface.dll</HintPath>
    </Reference>
    <Reference Include="Mapack">
      <HintPath>Libraries\Mapack.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
