<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace></RootNamespace>
    <AssemblyName>DWSIM.Thermodynamics.AdvancedEOS.GERG2008</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CapeOpen">
      <HintPath>..\..\lib\CapeOpen.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DWSIM.ExtensionMethods\DWSIM.ExtensionMethods.vbproj" />
    <ProjectReference Include="..\DWSIM.GlobalSettings\DWSIM.GlobalSettings.vbproj" />
    <ProjectReference Include="..\DWSIM.Interfaces\DWSIM.Interfaces.vbproj" />
    <ProjectReference Include="..\DWSIM.SharedClasses\DWSIM.SharedClasses.vbproj" />
    <ProjectReference Include="..\DWSIM.Thermodynamics\DWSIM.Thermodynamics.vbproj" />
  </ItemGroup>

</Project>
