<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DWSIM.FileStorage</RootNamespace>
    <AssemblyName>DWSIM.FileStorage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DWSIM.Interfaces\DWSIM.Interfaces.vbproj" />
    <ProjectReference Include="..\DWSIM.SharedClasses\DWSIM.SharedClasses.vbproj" />
  </ItemGroup>

</Project>
