<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DWSIM.Tools.ApiSurfaceDiff</RootNamespace>
    <AssemblyName>ApiSurfaceDiff</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reflection.MetadataLoadContext" />
  </ItemGroup>

</Project>
