Imports System.Diagnostics
Imports System.IO
Imports System.Net
Imports System.Net.WebSockets
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Threading
Imports System.Xml.Serialization

' =========================================================================
' Configuration data object (XML-serialisable)
' =========================================================================

''' <summary>All settings for the DWSIM Assistant integration.</summary>
<XmlRoot("DWSIMAssistantConfig")>
Public Class DWSIMAssistantConfig

    ' Connection
    <XmlElement> Public Property ServerUrl As String = "http://localhost:5834"
    <XmlElement> Public Property Language As String = "en"
    <XmlElement> Public Property DefaultBackend As String = "local"

    ' Local Ollama
    <XmlElement> Public Property OllamaPort As Integer = 0       ' 0 = default 11434
    <XmlElement> Public Property OllamaModel As String = ""      ' active model reported by server

    ' OpenAI
    <XmlElement> Public Property OpenAiKey As String = ""
    <XmlElement> Public Property OpenAiModel As String = "gpt-4o"

    ' Anthropic (Claude)
    <XmlElement> Public Property AnthropicKey As String = ""
    <XmlElement> Public Property AnthropicModel As String = "claude-sonnet-4-5"

    ' Custom / OpenAI-compatible endpoint
    <XmlElement> Public Property CustomEndpoint As String = ""
    <XmlElement> Public Property CustomKey As String = ""
    <XmlElement> Public Property CustomModel As String = ""

    ' PI Data Archive
    <XmlElement> Public Property PiServer As String = ""
    <XmlElement> Public Property PiUsername As String = ""
    <XmlElement> Public Property PiPassword As String = ""
    <XmlElement> Public Property PiDomain As String = ""

    ' OPC UA
    <XmlElement> Public Property OpcUrl As String = ""
    <XmlElement> Public Property OpcUsername As String = ""
    <XmlElement> Public Property OpcPassword As String = ""
    <XmlElement> Public Property OpcSecurityPolicy As String = "None"
    <XmlElement> Public Property OpcSecurityMode As String = "None"

    ' Runtime flags (not persisted, filled by FetchSettingsFromServerAsync)
    <XmlIgnore> Public Property OpenAiConfigured As Boolean = False
    <XmlIgnore> Public Property AnthropicConfigured As Boolean = False
    <XmlIgnore> Public Property CustomConfigured As Boolean = False
    <XmlIgnore> Public Property PiConfigured As Boolean = False
    <XmlIgnore> Public Property OpcConfigured As Boolean = False

End Class


''' <summary>
''' Full result of an LLM call: assembled text plus the usage / timing block
''' the server emits in its <c>done</c> event. Callers that only need the
''' text can keep using <see cref="LLMClient.Ask"/> / <see cref="LLMClient.AskAsync"/>.
''' </summary>
Public Class AskResult

    ''' <summary>Final assembled response text (after any after-response middleware).</summary>
    Public Property Text As String = ""

    ''' <summary>Tokens consumed by the input context (system prompt + history + user message).</summary>
    Public Property PromptTokens As Integer = 0

    ''' <summary>Tokens generated by the model (decode phase only - what dictates tok/s).</summary>
    Public Property CompletionTokens As Integer = 0

    ''' <summary>Sum of prompt + completion tokens, as reported by the backend.</summary>
    Public Property TotalTokens As Integer = 0

    ''' <summary>Anthropic prompt-cache hit count (0 for other backends).</summary>
    Public Property CacheReadTokens As Integer = 0

    ''' <summary>Anthropic prompt-cache miss / fill count (0 for other backends).</summary>
    Public Property CacheCreationTokens As Integer = 0

    ''' <summary>Wall-clock seconds the server measured for the whole turn (LLM + tools).</summary>
    Public Property ElapsedSeconds As Double = 0

    ''' <summary>Throughput estimate: <see cref="CompletionTokens"/> / <see cref="ElapsedSeconds"/>.</summary>
    Public Property TokensPerSecond As Double = 0

    ''' <summary>Server-active backend at done-time: <c>local</c> | <c>azure</c> | <c>openai</c> | <c>claude</c> | <c>custom</c>.</summary>
    Public Property Backend As String = ""

    ''' <summary>Concrete model name the server reported in the done event.</summary>
    Public Property ModelUsed As String = ""

    ''' <summary>True when the user cancelled mid-flight.</summary>
    Public Property Cancelled As Boolean = False

    ''' <summary>Non-empty when the server emitted an <c>error</c> event. <see cref="Text"/> mirrors it as <c>"[Error] …"</c> for callers that ignore this field.</summary>
    Public Property [Error] As String = ""

End Class

' =========================================================================
' Singleton client module
' =========================================================================

''' <summary>
''' Singleton client for the DWSIM Assistant HTTP/WebSocket API.
''' All members are implicitly Shared (VB.NET Module).
''' </summary>
Public Class LLMClient

    Private Const DefaultTimeoutMs As Integer = 10000

    Shared Sub New()
        ' Ensure TLS 1.2 is enabled (required by most remote endpoints on .NET 4.x).
        Try
            ServicePointManager.SecurityProtocol = ServicePointManager.SecurityProtocol Or
                                                   SecurityProtocolType.Tls12
        Catch
        End Try
    End Sub

    ''' <summary>Active configuration. Populate via InitAsync() or LoadConfig().</summary>
    Public Config As New DWSIMAssistantConfig()

    ''' <summary>
    ''' Per-launch auth token expected by the Python assistant on port 5834.
    ''' DWSIM mints this in ApplicationEvents.vb and exports it to the
    ''' assistant.exe via DWSIM_ASSISTANT_TOKEN. Both HTTP fetches (X-DWSIM-Token
    ''' header) and the chat WebSocket (?token=<guid>) need it once the auth
    ''' gate is enabled, otherwise the server returns 401 / 403.
    ''' </summary>
    Private Function GetAuthToken() As String
        Try
            Dim t = Environment.GetEnvironmentVariable("DWSIM_ASSISTANT_TOKEN",
                                                        EnvironmentVariableTarget.Process)
            If String.IsNullOrEmpty(t) Then Return ""
            Return t.Trim()
        Catch
            Return ""
        End Try
    End Function

    Private Class HttpResult
        Public Success As Boolean
        Public Body As String = ""
    End Class

    ''' <summary>Issue an HTTP request via HttpWebRequest. Returns body + success flag; never throws.</summary>
    Private Async Function SendAsync(method As String,
                                     url As String,
                                     Optional jsonBody As String = Nothing,
                                     Optional timeoutMs As Integer = DefaultTimeoutMs,
                                     Optional ct As CancellationToken = Nothing) As Task(Of HttpResult)

        Dim result As New HttpResult()
        Dim request As HttpWebRequest = Nothing
        Dim ctReg As CancellationTokenRegistration = Nothing

        Try
            request = DirectCast(WebRequest.Create(url), HttpWebRequest)
            request.Method = method
            request.Timeout = timeoutMs
            request.ReadWriteTimeout = timeoutMs
            request.KeepAlive = False

            ' Inject the per-launch auth token expected by the Python server.
            ' Without this every request to dwsim-assistant.exe gets 401 once
            ' DWSIM_ASSISTANT_TOKEN is set in the parent process env.
            Dim tok = GetAuthToken()
            If Not String.IsNullOrEmpty(tok) Then
                request.Headers("X-DWSIM-Token") = tok
            End If

            If ct <> Nothing AndAlso ct.CanBeCanceled Then
                Dim reqRef = request
                ctReg = ct.Register(Sub()
                                        Try : reqRef.Abort() : Catch : End Try
                                    End Sub)
            End If

            If jsonBody IsNot Nothing Then
                request.ContentType = "application/json"
                Dim body As Byte() = Encoding.UTF8.GetBytes(jsonBody)
                Using rs = Await Task.Factory.FromAsync(Of Stream)(AddressOf request.BeginGetRequestStream,
                                                                  AddressOf request.EndGetRequestStream,
                                                                  Nothing)
                    Await rs.WriteAsync(body, 0, body.Length)
                End Using
            End If

            Using response = DirectCast(Await Task.Factory.FromAsync(Of WebResponse)(AddressOf request.BeginGetResponse,
                                                                                     AddressOf request.EndGetResponse,
                                                                                     Nothing),
                                        HttpWebResponse)
                Using stream = response.GetResponseStream()
                    Using reader As New StreamReader(stream, Encoding.UTF8)
                        result.Body = Await reader.ReadToEndAsync()
                    End Using
                End Using
                Dim code As Integer = CInt(response.StatusCode)
                result.Success = (code >= 200 AndAlso code < 300)
            End Using

        Catch wex As WebException
            Try
                If wex.Response IsNot Nothing Then
                    Using stream = wex.Response.GetResponseStream()
                        If stream IsNot Nothing Then
                            Using reader As New StreamReader(stream, Encoding.UTF8)
                                result.Body = reader.ReadToEnd()
                            End Using
                        End If
                        wex.Response.Close()
                    End Using
                End If
            Catch
            End Try
        Catch ex As Exception
            Debug("[Client] SendAsync: " & ex.Message)
        Finally
            Try : ctReg.Dispose() : Catch : End Try
        End Try

        Return result
    End Function

    Private Function GetAsync(url As String,
                              Optional timeoutMs As Integer = DefaultTimeoutMs,
                              Optional ct As CancellationToken = Nothing) As Task(Of HttpResult)
        Return SendAsync("GET", url, Nothing, timeoutMs, ct)
    End Function

#Region "Initialisation"

    Public Async Function InitAsync() As Task
        Await FetchSettingsFromServerAsync()
    End Function

#End Region

#Region "Server sync - read current server state"

    ''' <summary>
    ''' Reads the server's active settings (GET /api-keys + GET /session) and
    ''' updates Config with non-secret fields: models, endpoints, backend, flags.
    ''' API keys in Config are NOT overwritten (server returns masked values).
    ''' Call this whenever the user may have changed settings via the web UI.
    ''' </summary>
    Public Async Function FetchSettingsFromServerAsync() As Task(Of Boolean)
        Try
            Using cts As New CancellationTokenSource(TimeSpan.FromSeconds(15))

                ' ── GET /api-keys ─────────────────────────────────────────
                Dim keysResp = Await GetAsync(Config.ServerUrl & "/api-keys", 15000, cts.Token)
                If keysResp.Success Then
                    Dim keysJson = keysResp.Body

                    ' Models (always overwrite - server is source of truth)
                    Dim ollamaUrl = JStr(keysJson, "ollama_url")
                    If Not String.IsNullOrEmpty(ollamaUrl) Then
                        ' Extract port from "http://localhost:NNNN"
                        Dim portMatch = Regex.Match(ollamaUrl, ":(\d+)$")
                        If portMatch.Success Then
                            Dim p As Integer
                            If Integer.TryParse(portMatch.Groups(1).Value, p) AndAlso p <> 11434 Then
                                Config.OllamaPort = p
                            End If
                        End If
                    End If

                    OverwriteIfNotEmpty(Config.OpenAiModel, JStr(keysJson, "openai_model"), Sub(v) Config.OpenAiModel = v)
                    OverwriteIfNotEmpty(Config.AnthropicModel, JStr(keysJson, "anthropic_model"), Sub(v) Config.AnthropicModel = v)
                    OverwriteIfNotEmpty(Config.CustomEndpoint, JStr(keysJson, "custom_endpoint"), Sub(v) Config.CustomEndpoint = v)
                    OverwriteIfNotEmpty(Config.CustomModel, JStr(keysJson, "custom_model"), Sub(v) Config.CustomModel = v)

                    ' PI / OPC endpoints (non-secret)
                    OverwriteIfNotEmpty(Config.PiServer, JStr(keysJson, "pi_server"), Sub(v) Config.PiServer = v)
                    OverwriteIfNotEmpty(Config.PiUsername, JStr(keysJson, "pi_username"), Sub(v) Config.PiUsername = v)
                    OverwriteIfNotEmpty(Config.PiDomain, JStr(keysJson, "pi_domain"), Sub(v) Config.PiDomain = v)
                    OverwriteIfNotEmpty(Config.OpcUrl, JStr(keysJson, "opc_url"), Sub(v) Config.OpcUrl = v)
                    OverwriteIfNotEmpty(Config.OpcUsername, JStr(keysJson, "opc_username"), Sub(v) Config.OpcUsername = v)
                    OverwriteIfNotEmpty(Config.OpcSecurityPolicy, JStr(keysJson, "opc_security_policy"), Sub(v) Config.OpcSecurityPolicy = v)
                    OverwriteIfNotEmpty(Config.OpcSecurityMode, JStr(keysJson, "opc_security_mode"), Sub(v) Config.OpcSecurityMode = v)

                    ' Runtime flags
                    Config.OpenAiConfigured = JBool(keysJson, "openai_configured")
                    Config.AnthropicConfigured = JBool(keysJson, "anthropic_configured")
                    Config.CustomConfigured = JBool(keysJson, "custom_configured")
                    Config.PiConfigured = JBool(keysJson, "pi_configured")
                    Config.OpcConfigured = JBool(keysJson, "opc_configured")
                End If

                ' ── GET /session ──────────────────────────────────────────
                Dim sessResp = Await GetAsync(Config.ServerUrl & "/session", 15000, cts.Token)
                If sessResp.Success Then
                    Dim sessJson = sessResp.Body
                    Dim backend = JStr(sessJson, "backend")
                    If Not String.IsNullOrEmpty(backend) Then
                        Config.DefaultBackend = backend
                    End If
                    Dim lang = JStr(sessJson, "language")
                    If Not String.IsNullOrEmpty(lang) Then
                        Config.Language = lang
                    End If
                End If

                ' ── GET /session/model (active Ollama model) ──────────────
                Dim modelResp = Await GetAsync(Config.ServerUrl & "/models", 15000, cts.Token)
                If modelResp.Success Then
                    Dim modelJson = modelResp.Body
                    Dim active = JStr(modelJson, "active_model")
                    If Not String.IsNullOrEmpty(active) Then
                        Config.OllamaModel = active
                    End If
                End If

            End Using
            Return True
        Catch ex As Exception
            Debug("[Client] FetchSettingsFromServerAsync: " & ex.Message)
            Return False
        End Try
    End Function

#End Region

#Region "Server sync - write current config to server"

    ''' <summary>
    ''' Push all API key and integration settings to the running server (POST /api-keys)
    ''' then switch the backend (PATCH /session).
    ''' </summary>
    Public Async Function ApplyConfigAsync(Optional cfg As DWSIMAssistantConfig = Nothing) As Task
        If cfg Is Nothing Then cfg = Config
        Dim fields() As String = {
                JInt("ollama_port", cfg.OllamaPort),
                JS("openai_key", cfg.OpenAiKey),
                JS("openai_model", cfg.OpenAiModel),
                JS("anthropic_key", cfg.AnthropicKey),
                JS("anthropic_model", cfg.AnthropicModel),
                JS("custom_endpoint", cfg.CustomEndpoint),
                JS("custom_key", cfg.CustomKey),
                JS("custom_model", cfg.CustomModel),
                JS("pi_server", cfg.PiServer),
                JS("pi_username", cfg.PiUsername),
                JS("pi_password", cfg.PiPassword),
                JS("pi_domain", cfg.PiDomain),
                JS("opc_url", cfg.OpcUrl),
                JS("opc_username", cfg.OpcUsername),
                JS("opc_password", cfg.OpcPassword),
                JS("opc_security_policy", cfg.OpcSecurityPolicy),
                JS("opc_security_mode", cfg.OpcSecurityMode)
            }
        Dim json As String = "{" & String.Join(",", fields) & "}"
        Try
            Await SendAsync("POST", cfg.ServerUrl & "/api-keys", json)
            Await SetBackendAsync(cfg.DefaultBackend)
        Catch ex As Exception
            Debug("[Client] ApplyConfigAsync: " & ex.Message)
        End Try
    End Function

    ''' <summary>Switch the active LLM backend: local | openai | claude | custom | azure.</summary>
    Public Async Function SetBackendAsync(backend As String) As Task
        Try
            Dim json As String = "{" & JS("backend", backend) & "}"
            Await SendAsync("PATCH", Config.ServerUrl & "/session", json)
            Config.DefaultBackend = backend
        Catch ex As Exception
            Debug("[Client] SetBackendAsync: " & ex.Message)
        End Try
    End Function

#End Region

#Region "LLM call interface"

    ''' <summary>
    ''' Synchronous LLM call. Blocks the calling thread until the full response arrives.
    ''' Safe to use from IronPython scripts and non-UI contexts.
    ''' Prefer AskAsync in async/UI code.
    ''' </summary>
    ''' <remarks>
    ''' Wraps AskAsync in <see cref="Task.Run"/> so that the inner awaits do NOT
    ''' capture the calling thread's SynchronizationContext. Without this wrap,
    ''' calling Ask() from the UI thread (typical when invoked from an IronPython
    ''' script bound to a button click) deadlocks: the UI thread blocks on
    ''' GetResult(), every continuation inside AskAsync queues back to that same
    ''' UI thread, and the WebSocket receive loop never advances. The server
    ''' then trips its ws_ping_timeout (20 s by default) and aborts the
    ''' connection - surfacing as WSAECONNABORTED ("connection aborted by the
    ''' host software"). The deadlock only manifests on slow backends because
    ''' fast cloud responses complete before the 20 s ping window expires.
    ''' </remarks>
    Public Function Ask(prompt As String,
                        Optional model As String = "",
                        Optional lang As String = "") As String
        Return Task.Run(Function() AskAsync(prompt, model, lang)).
                    ConfigureAwait(False).GetAwaiter().GetResult()
    End Function

    ''' <summary>
    ''' Synchronous LLM call returning the full <see cref="AskResult"/> with
    ''' real-time progress updates. Same UI-thread-safe wrap as <see cref="Ask"/>.
    ''' </summary>
    ''' <param name="onProgress">Invoked from a background thread for each
    ''' <c>stream_progress</c> event the server emits during generation. The
    ''' three arguments are <c>(tokensSoFar, elapsedSeconds, tokensPerSecond)</c>.
    ''' Marshall to the UI thread yourself if you need to update controls.</param>
    Public Function AskWithStats(prompt As String,
                                 Optional model As String = "",
                                 Optional lang As String = "",
                                 Optional onProgress As Action(Of Integer, Double, Double) = Nothing
                                 ) As AskResult
        Return Task.Run(Function() AskWithStatsAsync(prompt, model, lang, Nothing, onProgress)).
                    ConfigureAwait(False).GetAwaiter().GetResult()
    End Function

    ''' <summary>
    ''' Asynchronous streaming LLM call via WebSocket.
    ''' Calls <paramref name="onChunk"/> for each received text fragment.
    ''' Returns the complete concatenated response when the stream ends.
    ''' Uses the server's currently active backend and model by default.
    ''' </summary>
    Public Async Function AskAsync(prompt As String,
                                   Optional model As String = "",
                                   Optional lang As String = "",
                                   Optional onChunk As Action(Of String) = Nothing,
                                   Optional ct As CancellationToken = Nothing) As Task(Of String)
        Dim r = Await AskWithStatsAsync(prompt, model, lang, onChunk, Nothing, ct).
                      ConfigureAwait(False)
        Return r.Text
    End Function

    ''' <summary>
    ''' Asynchronous streaming LLM call returning the full <see cref="AskResult"/>
    ''' (text + token usage + timing + backend / model). Real-time tok/s readouts
    ''' are delivered via <paramref name="onProgress"/>; final stats are on the
    ''' returned <see cref="AskResult"/>.
    ''' </summary>
    ''' <param name="onChunk">Invoked for each <c>token</c> event with the
    ''' incremental text fragment (live streaming display).</param>
    ''' <param name="onProgress">Invoked for each <c>stream_progress</c> event
    ''' with <c>(tokensSoFar, elapsedSeconds, tokensPerSecond)</c>. Throttled
    ''' server-side to ~4 emits/second.</param>
    Public Async Function AskWithStatsAsync(prompt As String,
                                            Optional model As String = "",
                                            Optional lang As String = "",
                                            Optional onChunk As Action(Of String) = Nothing,
                                            Optional onProgress As Action(Of Integer, Double, Double) = Nothing,
                                            Optional ct As CancellationToken = Nothing) As Task(Of AskResult)

        Dim result As New AskResult()

        ' All awaits below use ConfigureAwait(False) so continuations run on
        ' the thread pool, not the calling SynchronizationContext. Combined
        ' with the Task.Run wrap in Ask(), this avoids UI-thread deadlocks
        ' when the assistant takes longer than the server's ws_ping_timeout.
        Await FetchSettingsFromServerAsync().ConfigureAwait(False)

        If String.IsNullOrWhiteSpace(model) Then model = EffectiveModel()
        If String.IsNullOrWhiteSpace(lang) Then lang = Config.Language
        Dim cancelTok As CancellationToken = If(ct = Nothing, CancellationToken.None, ct)

        Dim wsUrl As String = Config.ServerUrl _
                .Replace("http://", "ws://") _
                .Replace("https://", "wss://") & "/ws"

        ' Append the per-launch auth token as a query parameter - the server's
        ' /ws handler validates it and rejects with WebSocket close code 4401
        ' (manifesting as a 403 "Forbidden" from the underlying handshake)
        ' when DWSIM_ASSISTANT_TOKEN is set but the token is missing.
        Dim wsTok = GetAuthToken()
        If Not String.IsNullOrEmpty(wsTok) Then
            wsUrl = wsUrl & "?token=" & Uri.EscapeDataString(wsTok)
        End If

        Dim ws As New ClientWebSocket()
        Try
            Await ws.ConnectAsync(New Uri(wsUrl), cancelTok).ConfigureAwait(False)

            ' Send the user message
            Dim reqJson As String = "{" & JS("message", prompt) & "," &
                                          JS("model", model) & "," &
                                          JS("language", lang) & "}"
            Dim reqBytes As Byte() = Encoding.UTF8.GetBytes(reqJson)
            Await ws.SendAsync(New ArraySegment(Of Byte)(reqBytes),
                               WebSocketMessageType.Text, True, cancelTok).
                    ConfigureAwait(False)

            ' Accumulate multi-frame messages
            Dim frameBuf As New StringBuilder()
            Dim recvBuf(65535) As Byte
            Dim finalText As String = ""

            Do While ws.State = WebSocketState.Open
                Dim seg As New ArraySegment(Of Byte)(recvBuf)
                Dim r = Await ws.ReceiveAsync(seg, cancelTok).ConfigureAwait(False)

                If r.MessageType = WebSocketMessageType.Close Then Exit Do

                frameBuf.Append(Encoding.UTF8.GetString(recvBuf, 0, r.Count))

                ' Only process when a complete WebSocket frame arrives
                If Not r.EndOfMessage Then Continue Do

                Dim frame As String = frameBuf.ToString()
                frameBuf.Clear()

                ' Parse event type
                Dim evType As String = JStr(frame, "type").ToLowerInvariant()

                Select Case evType

                    Case "token"
                        ' Incremental text chunk from the LLM
                        Dim chunk As String = JStr(frame, "content")
                        onChunk?.Invoke(chunk)

                    Case "stream_progress"
                        ' Live tok/s update emitted ~every 250 ms by the
                        ' server while the active backend is generating.
                        ' Surface to the caller as (tokens, elapsed_s, tps).
                        If onProgress IsNot Nothing Then
                            Dim tokens As Integer = CInt(JNum(frame, "tokens"))
                            Dim elapsed As Double = JNum(frame, "elapsed_s")
                            Dim tps As Double = If(elapsed > 0, tokens / elapsed, 0)
                            Try
                                onProgress.Invoke(tokens, elapsed, tps)
                            Catch
                                ' Caller threw - don't kill the receive loop
                            End Try
                        End If

                    Case "done"
                        ' Server sends the complete final response in "full_response"
                        Dim full As String = JStr(frame, "full_response")
                        If String.IsNullOrEmpty(full) Then
                            ' Fallback: try "content" (older server versions)
                            full = JStr(frame, "content")
                        End If
                        finalText = full
                        ' Capture the overall stats block. JNum looks for the
                        ' first match of each key - the done frame's flat /
                        ' nested layout has unique keys (prompt_tokens lives
                        ' only inside `usage`), so this is unambiguous.
                        result.PromptTokens = CInt(JNum(frame, "prompt_tokens"))
                        result.CompletionTokens = CInt(JNum(frame, "completion_tokens"))
                        result.TotalTokens = CInt(JNum(frame, "total_tokens"))
                        result.CacheReadTokens = CInt(JNum(frame, "cache_read_tokens"))
                        result.CacheCreationTokens = CInt(JNum(frame, "cache_creation_tokens"))
                        result.ElapsedSeconds = JNum(frame, "elapsed_s")
                        If result.ElapsedSeconds > 0 Then
                            result.TokensPerSecond = result.CompletionTokens / result.ElapsedSeconds
                        End If
                        result.Backend = JStr(frame, "backend")
                        result.ModelUsed = JStr(frame, "model_used")
                        Exit Do     ' ← clean exit

                    Case "replace"
                        ' After-response middleware replaced the text
                        finalText = JStr(frame, "content")

                    Case "error"
                        Dim errMsg As String = JStr(frame, "content")
                        Debug("[Client] server error: " & errMsg)
                        finalText = "[Error] " & errMsg
                        result.Error = errMsg
                        Exit Do

                    Case "cancelled"
                        finalText = ""
                        result.Cancelled = True
                        Exit Do

                        ' tool_call, tool_result, thinking, status, etc. → ignore

                End Select
            Loop

            If ws.State = WebSocketState.Open Then
                Await ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "done", CancellationToken.None).
                        ConfigureAwait(False)
            End If
            ws.Dispose()

            result.Text = finalText
            Return result

        Catch ex As Exception
            Debug("[Client] AskAsync: " & ex.Message)
            Try
                If ws.State = WebSocketState.Open Then
                    ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "done", CancellationToken.None).GetAwaiter().GetResult()
                End If
            Catch
            End Try
            ws.Dispose()
            result.Text = "[Error] " & ex.Message
            result.Error = ex.Message
            Return result
        End Try
    End Function

#End Region

#Region "Status helpers"

    ''' <summary>Returns True if the server responds on /session within 3 seconds.</summary>
    Public Async Function IsServerRunningAsync() As Task(Of Boolean)
        Try
            Using cts As New CancellationTokenSource(TimeSpan.FromSeconds(3))
                Dim resp = Await GetAsync(Config.ServerUrl & "/session", 3000, cts.Token)
                Return resp.Success
            End Using
        Catch
            Return False
        End Try
    End Function

    ''' <summary>Open the DWSIM Assistant web UI in the default browser.</summary>
    Public Sub OpenInBrowser()
        Try
            System.Diagnostics.Process.Start(
                New System.Diagnostics.ProcessStartInfo(Config.ServerUrl) With {
                    .UseShellExecute = True
                })
        Catch ex As Exception
            Debug("[Client] OpenInBrowser: " & ex.Message)
        End Try
    End Sub

#End Region

#Region "Private helpers"

    ''' <summary>
    ''' Returns the model name that matches the server's current active backend.
    ''' Falls back to locally configured values.
    ''' </summary>
    Private Function EffectiveModel() As String
        Select Case Config.DefaultBackend.ToLowerInvariant()
            Case "openai" : Return Config.OpenAiModel
            Case "claude" : Return Config.AnthropicModel
            Case "custom" : Return Config.CustomModel
            Case "azure" : Return Config.CustomModel          ' azure uses custom model field
            Case Else       ' "local" / Ollama
                If Not String.IsNullOrEmpty(Config.OllamaModel) Then Return Config.OllamaModel
                ' Safe fallback: first managed model that's lightweight enough
                ' to run on CPU without GPU. Keep this in sync with the
                ' MANAGED_MODELS_SPEC list in server.py - qwen2.5:7b was
                ' removed from that list in favour of the qwen3.x family.
                Return "qwen3.5:4b"
        End Select
    End Function

    ''' <summary>Only update a config property if the new value is non-empty.</summary>
    Private Sub OverwriteIfNotEmpty(current As String, newVal As String, setter As Action(Of String))
        If Not String.IsNullOrEmpty(newVal) Then setter(newVal)
    End Sub

    ' ── JSON field builders ───────────────────────────────────────────────

    ''' <summary>JSON string field: "key":"escaped_value"</summary>
    Private Function JS(key As String, value As String) As String
        Return $"""{key}"":""{Esc(value)}"""
    End Function

    ''' <summary>JSON integer field: "key":number</summary>
    Private Function JInt(key As String, value As Integer) As String
        Return $"""{key}"":{value}"
    End Function

    ' ── Lightweight JSON readers (no external dependency) ─────────────────

    ''' <summary>
    ''' Extract a string value from a flat JSON object.
    ''' Handles "key":"value" and "key": "value" (with whitespace).
    ''' Returns "" when the key is absent or the value is null/empty.
    ''' </summary>
    Private Function JStr(json As String, key As String) As String
        If String.IsNullOrEmpty(json) Then Return ""
        ' Match: "key" : "value" where value may contain \-escaped chars
        Dim pattern As String = """" & Regex.Escape(key) & """\s*:\s*""((?:[^""\\]|\\.)*)"""
        Dim m = Regex.Match(json, pattern, RegexOptions.Singleline)
        If Not m.Success Then Return ""
        ' Unescape common JSON escape sequences
        Return JsonUnescape(m.Groups(1).Value)
    End Function

    ''' <summary>
    ''' Escapes a string for safe embedding as a JSON string value:
    ''' backslashes, double-quotes, and newline characters are escaped.
    ''' Returns an empty string when <paramref name="s"/> is <see langword="Nothing"/>.
    ''' </summary>
    ''' <param name="s">The raw string to escape.</param>
    ''' <returns>A JSON-safe string (without surrounding quotes).</returns>
    Private Function JsonEscape(s As String) As String
        If s Is Nothing Then Return ""
        Dim sb As New StringBuilder(s.Length + 32)
        For Each c As Char In s
            Select Case c
                Case "\"c : sb.Append("\\")
                Case """"c : sb.Append("\""")
                Case vbLf(0) : sb.Append("\n")
                Case vbCr(0) : ' strip CR (keep only LF)
                Case vbTab(0) : sb.Append("\t")
                Case Else
                    If Char.IsControl(c) Then
                        ' Escape any remaining control char as \uXXXX
                        sb.Append("\u").Append(Convert.ToInt32(c).ToString("x4"))
                    Else
                        sb.Append(c)
                    End If
            End Select
        Next
        Return sb.ToString()
    End Function

    Private Function JsonUnescape(s As String) As String
        If String.IsNullOrEmpty(s) Then Return s
        Dim sb As New StringBuilder(s.Length)
        Dim i As Integer = 0
        Do While i < s.Length
            If s(i) = "\"c AndAlso i + 1 < s.Length Then
                Select Case s(i + 1)
                    Case """"c : sb.Append(""""c) : i += 2
                    Case "\"c : sb.Append("\"c) : i += 2
                    Case "/"c : sb.Append("/"c) : i += 2
                    Case "n"c : sb.Append(vbLf) : i += 2
                    Case "r"c : sb.Append(vbCr) : i += 2
                    Case "t"c : sb.Append(vbTab) : i += 2
                    Case "u"c
                        ' \uXXXX unicode escape
                        If i + 5 < s.Length Then
                            Dim hex As String = s.Substring(i + 2, 4)
                            Dim code As Integer
                            If Integer.TryParse(hex, Globalization.NumberStyles.HexNumber, Nothing, code) Then
                                sb.Append(Char.ConvertFromUtf32(code))
                                i += 6
                            Else
                                sb.Append(s(i)) : i += 1
                            End If
                        Else
                            sb.Append(s(i)) : i += 1
                        End If
                    Case Else
                        sb.Append(s(i + 1)) : i += 2
                End Select
            Else
                sb.Append(s(i)) : i += 1
            End If
        Loop
        Return sb.ToString()
    End Function


    ''' <summary>
    ''' Extract a numeric value (integer or float) from a JSON document.
    ''' Returns 0 when the key is absent or the value is not numeric.
    ''' Matches the FIRST occurrence; safe for the assistant's done frame
    ''' where every numeric key (prompt_tokens, completion_tokens, total_tokens,
    ''' elapsed_s, …) appears only once even when nested under <c>usage</c>.
    ''' </summary>
    Private Function JNum(json As String, key As String) As Double
        If String.IsNullOrEmpty(json) Then Return 0
        Dim pattern As String = """" & Regex.Escape(key) & """\s*:\s*(-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?)"
        Dim m = Regex.Match(json, pattern)
        If Not m.Success Then Return 0
        Dim v As Double
        If Double.TryParse(m.Groups(1).Value,
                           Globalization.NumberStyles.Float,
                           Globalization.CultureInfo.InvariantCulture, v) Then
            Return v
        End If
        Return 0
    End Function

    ''' <summary>
    ''' Extract a boolean value from a flat JSON object.
    ''' Returns True when the value is the JSON literal <c>true</c>.
    ''' </summary>
    Private Function JBool(json As String, key As String) As Boolean
        If String.IsNullOrEmpty(json) Then Return False
        Dim pattern As String = """" & Regex.Escape(key) & """\s*:\s*(true|false)"
        Dim m = Regex.Match(json, pattern, RegexOptions.IgnoreCase)
        Return m.Success AndAlso m.Groups(1).Value.ToLower() = "true"
    End Function

    ''' <summary>Escape a string for embedding inside a JSON string value.</summary>
    Private Function Esc(s As String) As String
        If String.IsNullOrEmpty(s) Then Return ""
        Return s.Replace("\", "\\").Replace("""", "\""").Replace(vbCr, "\r").Replace(vbLf, "\n")
    End Function

    Private Sub Debug(msg As String)
        System.Diagnostics.Debug.WriteLine(msg)
    End Sub

#End Region

#Region "Code-edit (vibe coding)"

    ' ─────────────────────────────────────────────────────────────────────────
    ' Code-edit endpoint binding - drives the AI Edit (Ctrl+K) feature in the
    ' IronPython script editors (FormScript and EditingForm_CustomUO_*).
    '
    ' Hits the synchronous /code/edit REST endpoint on the Python server. The
    ' server runs a bounded 3-iteration agent: it asks the LLM for a complete
    ' updated script, validates the syntax with Python's `compile()`, and
    ' retries with the error fed back if validation fails. By the time we get
    ' a response here, the code has either passed validation or the server
    ' gave up after 3 attempts (and `Validated = False` flags it).
    '
    ' The streaming variant /code/stream is NOT used here because the loop is
    ' fast enough (typically 3-15 s on cloud backends) that progress events
    ' don't justify the WebSocket overhead. If users complain about UI freeze
    ' on slow Ollama models we can add a streaming overload later.
    ' ─────────────────────────────────────────────────────────────────────────

    Public Async Function CodeEditAsync(instruction As String,
                                        currentCode As String,
                                        Optional isUOScript As Boolean = True,
                                        Optional language As String = "ironpython",
                                        Optional context As String = Nothing,
                                        Optional ct As CancellationToken = Nothing,
                                        Optional timeoutMs As Integer = 120000) _
                                        As Task(Of CodeEditResult)

        Dim result As New CodeEditResult()
        Dim sw = Stopwatch.StartNew()

        Try
            Dim ctxJson As String = If(String.IsNullOrEmpty(context), "{}", context)

            ' Hand-build the JSON to keep this file self-contained (no
            ' Newtonsoft.Json reference). The four user-supplied fields are
            ' escaped via JsonEscape; `context` is already JSON.
            Dim sb As New StringBuilder()
            sb.Append("{")
            sb.Append("""instruction"":""").Append(JsonEscape(instruction)).Append(""",")
            sb.Append("""current_code"":""").Append(JsonEscape(currentCode)).Append(""",")
            sb.Append("""language"":""").Append(JsonEscape(language)).Append(""",")
            sb.Append("""is_uo_script"":").Append(If(isUOScript, "true", "false")).Append(",")
            sb.Append("""context"":").Append(ctxJson)
            sb.Append("}")

            Dim resp = Await SendAsync("POST",
                                        Config.ServerUrl & "/code/edit",
                                        sb.ToString(),
                                        timeoutMs,
                                        ct)

            sw.Stop()
            result.ElapsedSeconds = sw.Elapsed.TotalSeconds

            If ct.IsCancellationRequested Then
                result.Cancelled = True
                Return result
            End If

            If Not resp.Success Then
                result.[Error] = If(String.IsNullOrEmpty(resp.Body),
                                    "Empty response from /code/edit (server unreachable?)",
                                    resp.Body)
                Return result
            End If

            ' Parse the response shape:
            '   { "code": "...", "explanation": "...",
            '     "validated": true|false,
            '     "validation_error": "..." | null }
            result.Code            = ExtractJsonString(resp.Body, "code")
            result.Explanation     = ExtractJsonString(resp.Body, "explanation")
            result.Validated       = ExtractJsonBool(resp.Body, "validated", False)
            result.ValidationError = ExtractJsonString(resp.Body, "validation_error")

        Catch ex As Exception
            sw.Stop()
            result.ElapsedSeconds = sw.Elapsed.TotalSeconds
            result.[Error] = ex.Message
            Debug("[Client] CodeEditAsync: " & ex.Message)
        End Try

        Return result
    End Function

    ' ── Lightweight JSON peekers - sufficient for our flat reply shape. ──
    ' Reuses the existing JsonUnescape instance helper defined earlier in
    ' this class (around line 698) so we don't duplicate the escape table.

    Private Function ExtractJsonString(json As String, key As String) As String
        If String.IsNullOrEmpty(json) Then Return ""
        ' Match: "key" : (null | "string-with-escapes")
        Dim pat As String = """" & Regex.Escape(key) & """\s*:\s*(?:null|""((?:\\.|[^""\\])*)"")"
        Dim m = Regex.Match(json, pat)
        If Not m.Success Then Return ""
        If m.Groups(1).Value = "" AndAlso m.Value.Contains("null") Then Return ""
        Return JsonUnescape(m.Groups(1).Value)
    End Function

    Private Function ExtractJsonBool(json As String, key As String, fallback As Boolean) As Boolean
        If String.IsNullOrEmpty(json) Then Return fallback
        Dim pat As String = """" & Regex.Escape(key) & """\s*:\s*(true|false)"
        Dim m = Regex.Match(json, pat)
        If Not m.Success Then Return fallback
        Return m.Groups(1).Value.Equals("true", StringComparison.OrdinalIgnoreCase)
    End Function

#End Region

End Class

''' <summary>
''' Result of a single AI code-edit call (Ctrl+K vibe coding). The Python
''' server's /code/edit endpoint runs a bounded 3-iteration agent that asks
''' the LLM for a complete updated script and self-validates each draft
''' before returning. <see cref="Validated"/> tells you whether the final
''' draft compiled cleanly; if False, <see cref="ValidationError"/> carries
''' the parser's complaint so the UI can show it next to the diff.
''' </summary>
Public Class CodeEditResult

    ''' <summary>Updated IronPython script returned by the LLM.</summary>
    Public Property Code As String = ""

    ''' <summary>Short prose explanation of what changed (model-generated).</summary>
    Public Property Explanation As String = ""

    ''' <summary>True if the returned code passed Python's `compile()` check.</summary>
    Public Property Validated As Boolean = False

    ''' <summary>SyntaxError text if validation failed; empty otherwise.</summary>
    Public Property ValidationError As String = ""

    ''' <summary>HTTP / network error if the call itself failed.</summary>
    Public Property [Error] As String = ""

    ''' <summary>Wall-clock time including all retry iterations.</summary>
    Public Property ElapsedSeconds As Double = 0

    ''' <summary>True if the caller's CancellationToken fired before completion.</summary>
    Public Property Cancelled As Boolean = False

End Class