<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DWSIM.Interfaces</RootNamespace>
    <AssemblyName>DWSIM.Interfaces</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Runtime.InteropServices" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" />
  </ItemGroup>

</Project>
