<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Daniel Medeiros</Authors>
    <Product>DWSIM Core Library (.NET 6)</Product>
    <Description>DWSIM Core Library containing Automation class and IFlowsheet/Flowsheetbase implementation.</Description>
    <Copyright>Copyright 2022 Daniel Wagner Oliveira de Medeiros</Copyright>
    <PackageProjectUrl>https://dwsim.org</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp.LGPLv2.Core" Version="1.8.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="OxyPlot.Core" Version="2.1.0" />
    <PackageReference Include="SkiaSharp" Version="2.88.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DWSIMCore.Foundation\DWSIMCore.Foundation.vbproj" />
  </ItemGroup>

</Project>
