// Decompiled with JetBrains decompiler
// Type: CapeOpen.ICapeUtilities
// Assembly: CapeOpen, Version=1.0.0.0, Culture=neutral, PublicKeyToken=90d5303f0e924b64
// MVID: 4E76E984-6CC8-4C13-98A0-D3FBAF2DEB87
// Assembly location: C:\Users\Daniel\source\repos\DanWBR\dwsim\DistPackages\Windows\CapeOpen.dll

using System.ComponentModel;
using System.Runtime.InteropServices;

namespace CapeOpen
{
  /// <summary>
  /// Interface that exposes a PMC's parameters, controls the PMC's lifecycle,
  /// provides access to the PME through the simulation context, and provides a
  /// means for the PME to edit the PMC.
  /// </summary>
  /// <remarks>
  /// <para>When a PME requires some kind of functionality, with the help of the
  /// CAPE-OPEN categories, the user is able to select and create a CO class which
  /// will expose the required CO interfaces. There is the need for the PME to
  /// exchange some information with this instance of the PMC. This information
  /// consists in a set of simple unrelated functionalities that will be useful for
  /// any kind of CAPE-OPEN component, since they will allow maximum integration
  /// between clients and servers. All these functionalities can be grouped in a
  /// single interface. Some of the functionalities to fulfil consist in exchanging
  /// interface references between the PMC and the PME. Instead of adding these
  /// properties to each business interfaces, it is much more convenient to
  /// add them to a single common interface which refers to the whole PMC.</para>
  /// <para>Furthermore, there is a need for getting parameters, editing and
  /// lifecycling.</para>
  /// <para>The interface should fulfil the following requirements:</para>
  /// <para>Parameters:</para>
  /// <para>So far, only Unit Operations can expose their public parameters, through
  /// property ICapeUnit.parameters, which returns a collection of parameters. This
  /// property allows COSEs to support design specs between two CAPE-OPEN Unit
  /// Operations. That means that the CAPE-OPEN interfaces are powerful enough to
  /// allow that the design spec of a given Unit Operation (exposed through public
  /// parameters) depends on transformations of public parameters exposed by other
  /// CAPE-OPEN Unit Operations. If also other components, such as Material Object,
  /// would be able to expose public parameters, the functionality the aforementioned
  /// described functionality could be extended. Other functionalities would be:
  /// </para>
  /// <para>(i) allowing optimizers to use a public variable exposed by any
  /// CAPE-OPEN component.</para>
  /// <para>(ii) Allow performing regression on the interaction parameters of a
  /// CAPE-OPEN Property Package.</para>
  /// <para>Centralising the property that accesses these collections in a single
  /// entry point, helps to clarify the life cycle usage standards for these
  /// collections. That means that it will be easier for the PMC clients to know
  /// how often they have to check whether the contents of these collections have
  /// changed (although the collection object will be valid until the PMC is
  /// destroyed). Setting general rules for the usage of these collections makes
  /// the business interface specifications more regular and simpler. Obviously,
  /// since too general rules may reduce flexibility, PMC specifications might point
  /// out exceptions to the general rule. Let’s see how would this affect the
  /// particular PMC specifications:</para>
  /// <para>Simulation context:</para>
  /// <para>So far, most of CAPE-OPEN interfaces have been designed to allow a
  /// client to access the functionality of a CAPE-OPEN component. Since clients
  /// will often be Simulation Environment, CAPE-OPEN components would benefit from
  /// using functionality provided by their client, a COSE for instance. These
  /// services provided by any PMEs are defined within the Simulation Context COSE
  /// Interface specification document.</para>
  /// <para>The following interfaces are designed:</para>
  /// <para>(i) Thermo Material Template Systems: Theses interface allows a PMC to
  /// choose between all the Thermo Material factories supported by the PME. These
  /// factories will allow the PMC to create a thermo material object associated to
  /// the elected Property Package (which can be CAPE-OPEN or not).</para>
  /// <para>(ii) Diagnostics: This interface will allow to integrate seamlessly the
  /// diagnostics messages generated by any PMC with the mechanisms supported by
  /// the PME to display this information to the user.</para>
  /// <para>(iii) COSEUtilities: In the same idea of this specification document,
  /// PME has also its own utilities interface in order to gather many basic
  /// operations. For instance that allows the PME to supply a list of standardised
  /// values.</para>
  /// <para>Edit:</para>
  /// <para>The Edit method defined by the UNIT specification proved to be very useful in
  /// order to provide Graphical User Interface (GUI) capabilities highly customized
  /// to each type of UNIT implementation. There’s no reason why other PMCs could
  /// not benefit of this capability. Obviously, when a PMC provides Edit
  /// functionality, being able to persist its state is a desired requirements, to
  /// prevent the user from having to repeatedly reconfigure the PMC.</para>
  /// <para>LifeCycle:</para>
  /// <para>There is probably no strict necessity to expose directly initialization
  /// nor destruction functions, since these should be invoked automatically by the
  /// used middleware (COM/CORBA). That is, the initialization could be performed
  /// in the constructor of the class and the destroy in its destructor. However,
  /// in some cases the client could need to invoke them explicitly. For example,
  /// all actions that could fail should be invoked by these methods. If these
  /// actions were places in the constructor or destructor, potential failures
  /// would cause memory leak, and they would be difficult to track, since it would
  /// not be clear if the component has been created/destroyed or not. Examples of
  /// cases where they are useful:</para>
  /// <para>(i) Initialize: The client might need to initialize a given set of PMC
  /// in a specific order, in case that there are dependencies between them. Some
  /// PMC may be wrappers to other components, or may need an external file to get
  /// initialized. This initialization process may often fail, or the user may even
  /// decide to cancel it. Moving these actions from the class constructor to the
  /// initialize method allows communicating the client that the construction of
  /// the component must be aborted in some cases.</para>
  /// <para>(ii) Destructors: The PMC primary object should destroy here all its secondary
  /// objects. Relying on the native destructor could cause deadlocks when loop
  /// references exist between PMC objects. See in the example diagram below that
  /// after the client releases its reference to the Unit Operation, both the Unit
  /// and the Parameter are being used by another objects. So, without an explicit
  /// terminate method, none of them would be ever terminated.</para>
  /// <para>Reference document: Utilities Common Interface</para>
  /// </remarks>
  [Description("ICapeUtilities Interface")]
  [Guid("678c0a9b-0100-11d2-a67d-00105a42887f")]
  [ComVisible(false)]
  [ComImport]
  public interface ICapeUtilities
  {
    /// <summary>Gets the component's collection of parameters.</summary>
    /// <remarks>
    /// <para>Return the collection of Public Unit Parameters (i.e.
    /// <see cref="T:CapeOpen.ICapeCollection" />.</para>
    /// <para>These are delivered as a collection of elements exposing the interface
    /// <see cref="T:CapeOpen.ICapeParameter" />. From there, the client could extract the
    /// <see cref="T:CapeOpen.ICapeParameterSpec" /> interface or any of the typed
    /// interfaces such as <see cref="T:CapeOpen.ICapeRealParameterSpec" />, once the client
    /// establishes that the Parameter is of type double.</para>
    /// </remarks>
    /// <value>The parameter collection of the unit operation.</value>
    /// <exception cref="T:CapeOpen.ECapeUnknown">The error to be raised when other error(s),  specified for this operation, are not suitable.</exception>
    /// <exception cref="T:CapeOpen.ECapeFailedInitialisation">ECapeFailedInitialisation</exception>
    /// <exception cref="T:CapeOpen.ECapeNoImpl">ECapeNoImpl</exception>
    [DispId(1)]
    [Description("Gets parameter collection")]
    object parameters { [return: MarshalAs(UnmanagedType.IDispatch)] get; }

    /// <summary>Sets the component's simulation context.</summary>
    /// <remarks>
    /// <para>Allows the PME to convey the PMC a reference to the former’s
    /// simulation  context. The simulation context will be PME objects which will
    /// expose a given set of CO interfaces. Each of these interfaces will allow
    /// the PMC to call back the PME in order to benefit from its exposed services
    /// (such as creation of material templates, diagnostics or measurement unit
    /// conversion). If the PMC does not support accessing the simulation context,
    /// it is recommended to raise the ECapeNoImpl error.</para>
    /// <para>Initially, this method was only present in the ICapeUnit interface.
    /// Since ICapeUtilities.SetSimulationContext is now available for any kind of
    /// PMC, ICapeUnit.SetSimulationContext is deprecated.</para>
    /// </remarks>
    /// <value>
    /// The reference to the PME’s simulation context class. For the PMC to use
    /// this class, this reference will have to be converted to each of the
    /// defined CO Simulation Context interfaces.
    /// </value>
    /// <exception cref="T:CapeOpen.ECapeUnknown">The error to be raised when other error(s),  specified for this operation, are not suitable.</exception>
    /// <exception cref="T:CapeOpen.ECapeFailedInitialisation">ECapeFailedInitialisation</exception>
    /// <exception cref="T:CapeOpen.ECapeInvalidArgument">To be used when an invalid argument value is passed, for example, an unrecognised Compound identifier or UNDEFINED for the props argument.</exception>
    /// <exception cref="T:CapeOpen.ECapeNoImpl">ECapeNoImpl</exception>
    [DispId(2)]
    [Description("Set the simulation context")]
    object simulationContext { [param: MarshalAs(UnmanagedType.IDispatch)] set; }

    /// <summary>
    /// The component is asked to configure itself. For example a Unit Operation might create ports and parameters during this call
    /// </summary>
    /// <remarks>
    /// <para>Initially, this method was only present in the ICapeUnit interface.
    /// Since ICapeUtilities.Initialize is now available for any kind of PMC,
    /// ICapeUnit. Initialize is deprecated.</para>
    /// <para>The PME will order the PMC to get initialized through this method.
    /// Any initialisation that could fail must be placed here. Initialize is
    /// guaranteed to be the first method called by the client (except low level
    /// methods such as class constructors or initialization persistence methods).
    /// Initialize has to be called once when the PMC is instantiated in a
    /// particular flowsheet.</para>
    /// <para>When the initialization fails, before signalling an error, the PMC
    /// must free all the resources that were allocated before the failure
    /// occurred. When the PME receives this error, it may not use the PMC
    /// anymore.</para>
    /// <para>The method terminate of the current interface must not either be
    /// called. Hence, the PME may only release the PMC through the middleware
    /// native mechanisms.</para>
    /// </remarks>
    /// <exception cref="T:CapeOpen.ECapeUnknown">The error to be raised when other error(s),  specified for this operation, are not suitable.</exception>
    /// <exception cref="T:CapeOpen.ECapeOutOfResources">ECapeOutOfResources</exception>
    /// <exception cref="T:CapeOpen.ECapeLicenceError">ECapeLicenceError</exception>
    /// <exception cref="T:CapeOpen.ECapeFailedInitialisation">ECapeFailedInitialisation</exception>
    /// <exception cref="T:CapeOpen.ECapeBadInvOrder">ECapeBadInvOrder</exception>
    [Description("Configuration has to take place here")]
    [DispId(3)]
    void Initialize();

    /// <summary>
    /// Clean-up tasks can be performed here. References to parameters and ports are released here.
    /// </summary>
    /// <remarks>
    /// <para>Initially, this method was only present in the ICapeUnit interface.
    /// Since ICapeUtilities.Terminate is now available for any kind of PMC,
    /// ICapeUnit.Terminate is deprecated.</para>
    /// <para>The PME will order the PMC to get destroyed through this method.
    /// Any uninitialization that could fail must be placed here. ‘Terminate’ is
    /// guaranteed to be the last method called by the client (except low level
    /// methods such as class destructors). ‘Terminate’ may be called at any time,
    /// but may be only called once.</para>
    /// <para>When this method returns an error, the PME should report the user.
    /// However, after that the PME is not allowed to use the PMC anymore.</para>
    /// <para>The Unit specification stated that “Terminate may check if the data
    /// has been saved and return an error if not.” It is suggested not to follow
    /// this recommendation, since it’s the PME responsibility to save the state
    /// of the PMC before terminating it. In the case that a user wants to close
    /// a simulation case without saving it, it’s better to leave the PME to
    /// handle the situation instead of each PMC providing a different
    /// implementation.</para>
    /// </remarks>
    /// <exception cref="T:CapeOpen.ECapeUnknown">The error to be raised when other error(s),  specified for this operation, are not suitable.</exception>
    /// <exception cref="T:CapeOpen.ECapeOutOfResources">ECapeOutOfResources</exception>
    /// <exception cref="T:CapeOpen.ECapeBadInvOrder">ECapeBadInvOrder</exception>
    [Description("Clean up has to take place here")]
    [DispId(4)]
    void Terminate();

    /// <summary>Displays the PMC graphic interface, if available.</summary>
    /// <remarks>
    /// The PMC displays its user interface and allows the Flowsheet User to
    /// interact with it. If no user interface is available it returns an error.
    /// </remarks>
    /// <exception cref="T:CapeOpen.ECapeUnknown">The error to be raised when other error(s),  specified for this operation, are not suitable.</exception>
    [Description("Displays the graphic interface")]
    [DispId(5)]
    void Edit();
  }
}
