<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DWSIM.DrawingTools.Point</RootNamespace>
    <AssemblyName>DWSIM.DrawingTools.Point</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DWSIM.Interfaces\DWSIM.Interfaces.vbproj" />
  </ItemGroup>

</Project>
