using OxyPlot;
public interface IUserInterfaceControls
{
    object CreateAndAddBoldLabelAndButtonRow(object container, string label, string buttonlabel, string imageResID, Action<object, EventArgs> command);
    object CreateAndAddButtonRow(object container, string buttonlabel, string imageResID, Action<object, EventArgs> command);
    object CreateAndAddCheckBoxRow(object container, string text, bool value, Action<object, EventArgs> command, Action keypress = null);
    object CreateAndAddColorPickerRow(object container, string text, object currval, Action<object, EventArgs> command);
    object CreateAndAddControlRow(object container, object control);
    object CreateAndAddDescriptionRow(object container, string text, bool forceLabel = false);
    object CreateAndAddDoubleTextBoxRow(object container, string numberformat, string text, string currval1, double currval2, Action<object, EventArgs> command, Action<object, EventArgs> command2);
    object CreateAndAddDropDownRow(object container, string text, List<string> options, int position, Action<object, EventArgs> command, Action keypress = null);
    object CreateAndAddDropDownRow(object container, string text, List<string> options, string selecteditem, Action<object, EventArgs> command, Action keypress = null);
    object CreateAndAddEditableDropDownRow(object container, string text, List<string> options, int position, Action<object, EventArgs> selectionchangedcommand, Action keypress = null);
    void CreateAndAddEmptySpace(object container);
    object CreateAndAddFullTextBoxRow(object container, string text, Action<object, EventArgs> command);
    object CreateAndAddLabelAndButtonRow(object container, string label, string buttonlabel, string imageResID, Action<object, EventArgs> command);
    void CreateAndAddLabelAndControlRow(object container, string label, object control);
    object CreateAndAddLabelAndTextBoxAndButtonRow(object container, string label, string textboxvalue, string buttonlabel, string imageResID, Action<object, EventArgs> txteditcommand, Action<object, EventArgs> command);
    object CreateAndAddLabelAndTextBoxAndButtonRow2(object container, string label, string textboxvalue, string buttonlabel, string imageResID, Action<object, EventArgs> txteditcommand, Action<object, EventArgs> command);
    object CreateAndAddLabelAndTwoButtonsRow(object container, string label, string buttonlabel, string imageResID, string buttonlabel2, string imageResID2, Action<object, EventArgs> command, Action<object, EventArgs> command2);
    object CreateAndAddLabelRow(object container, string text);
    object CreateAndAddLabelRow2(object container, string text);
    object CreateAndAddLabelRow3(object container, string text);
    object CreateAndAddListBoxRow(object container, int height, string[] listitems, Action<object, EventArgs> command);
    object CreateAndAddMultilineMonoSpaceTextBoxRow(object container, string text, int height, bool ro, Action<object, EventArgs> command);
    object CreateAndAddMultilineTextBoxRow(object container, string text, bool ro, bool autosized, Action<object, EventArgs> command);
    object CreateAndAddNumericEditorRow(object container, string text, double currval, double minval, double maxval, int decimalplaces, Action<object, EventArgs> command);
    object CreateAndAddStringEditorRow(object container, string text, string currval, Action<object, EventArgs> command, Action keypress = null);
    object CreateAndAddStringEditorRow2(object container, string text, string placeholder, string currval, Action<object, EventArgs> command);
    object CreateAndAddTextBoxAndTwoButtonsRow(object container, string label, string buttonlabel, string imageResID, string buttonlabel2, string imageResID2, Action<object, EventArgs> command0, Action<object, EventArgs> command, Action<object, EventArgs> command2);
    object CreateAndAddTextBoxRow(object container, string numberformat, string text, double currval, Action<object, EventArgs> command, Action keypress = null);
    object CreateAndAddTextBoxRow2(object container, string numberformat, string text, double currval, Action<object, EventArgs> command);
    object CreateAndAddThreeLabelsRow(object container, string text1, string text2, string text3);
    object CreateAndAddTwoButtonsRow(object container, string buttonlabel, string imageResID, string buttonlabel2, string imageResID2, Action<object, EventArgs> command, Action<object, EventArgs> command2);
    object CreateAndAddTwoLabelsRow(object container, string text1, string text2);
    object CreateAndAddTwoLabelsRow2(object container, string text1, string text2);
    object CreateDialog(object content, string title, int width = 0, int height = 0);
    object CreateDialogWithButtons(object content, string title, Action okclicked, int width = 0, int height = 0);
    PlotModel CreatePlotModel(double[] x, double[] y1, double[] y2, string title, string subtitle, string xtitle, string ytitle, string ytitle1, string ytitle2);
    PlotModel CreatePlotModel(double[] x, double[] y, string title, string subtitle, string xtitle, string ytitle);
    object GetDefaultContainer();
    object GetDefaultEditorForm(string title, int width, int height, object content);
    object GetDefaultEditorForm(string title, int width, int height, object content, bool scrollable);
    object GetDefaultTabbedForm(string title, int width, int height, object[] contents);
}