<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DWSIM.Thermodynamics.Databases.DDBStructureLink</RootNamespace>
    <AssemblyName>DWSIM.Thermodynamics.Databases.DDBStructureLink</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DWSIM.Interfaces\DWSIM.Interfaces.vbproj" />
    <ProjectReference Include="..\DWSIM.Thermodynamics\DWSIM.Thermodynamics.vbproj" />
  </ItemGroup>

</Project>
